{{- range .Values.domains }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nikto-scanner-{{ . | replace "." "-"}}
spec:
  schedule: "{{ $.Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nikto-scanner
            image: sammascanner/nikto:{{ $.Values.image.tag }}
            env:
              - name: TARGET
                value: "{{ . }}"
          restartPolicy: Never
---
{{ end }}