version: '2'
services:
  nmap:
    build: .
    image: sammascanner/nikto
    volumes:
      - ./:/scanner
    environment:
      - TARGET=grafana.fareonline.net
      - TUNING=23
      - PORT=443
    command: tail -f /etc/fstab
