services:
  nikto:
    build: .
    image: ghcr.io/samma-io/nikto:latest
    volumes:
      - ./out:/out
    environment:
      - TARGET=hellohippo.com
      - TUNING=23
      - PORT=443
      - SAMMA_IO_SCANNER=nikto
      - SAMMA_IO_ID=1234
      - SAMMA_IO_TAGS=scanner,prod
      - SAMMA_IO_JSON={}
      - TARGET_ID=
      - WRITE_TO_FILE=true
      - PARSER=nikto
      - NATS_ENABLED=False
      - NATS_URL=nats://localhost:4222
      - NATS_SUBJECT=scans
